# Generated by Django 5.0.4 on 2024-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="desc",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="publish_date",
            new_name="pub_date",
        ),
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=50),
        ),
    ]
